name: flutter_execution_utilities
description: A collection of execution control utilities for Flutter and Dart, including debounce, throttle, memoization, retry mechanisms, and more
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
  
dependencies:
  collection: ^1.19.0
